name: Reusable ArgoCD Sync

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: true
      branch:
        type: string
        required: true
      tagKey:
        type: string
        required: true
      skipRevision:
        type: boolean
        required: false
        default: false
      environment:
        type: string
        default: 'dev'
        required: false
      cluster:
        type: string
        required: false
      timeout:
        type: string
        default: '500'
        required: false
    secrets:
      CI_ARGOCD:
        required: true
      CI_SLACK_WEBHOOK:
        required: true
      CI_ARGOCD_SERVER:
        required: true
jobs:
  argocd:
    environment: ${{ inputs.environment }}
    name: "[ArgoCD]"
    runs-on: [self-hosted, "${{ inputs.environment }}"]
    steps:
      - name: "[ArgoCD]: set variables"
        id: vars
        run: |
          echo "APP_NAME=${{ contains(inputs.environment, 'env') && format('{0}-{1}', inputs.environment, inputs.app-name) || inputs.app-name}}" >> $GITHUB_ENV
          echo "NEW_APP_NAME=${{ inputs.cluster && format('{0}-{1}-${2}', inputs.environment, inputs.cluster, inputs.app-name) || null }}" >> $GITHUB_ENV
          echo "ARGOCD_AUTH_TOKEN=${{ secrets.CI_ARGOCD }}" >> $GITHUB_ENV
          echo "ARGOCD_SERVER=${{ secrets.CI_ARGOCD_SERVER }}" >> $GITHUB_ENV
          echo 'ARGOCD_OPTS="--grpc-web"' >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA::6}" >> $GITHUB_ENV
          echo "SLACK_ICON=https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png"
          if [[ "${{ inputs.environment }}" == "dev" ]]; then
            echo "SLACK_ICON=https://firefly-app-assets.s3.us-east-1.amazonaws.com/logo/serenity.png"
          fi
      - name: Clone helm-values repository
        if: ${{ env.NEW_APP_NAME }}
        uses: actions/checkout@v4
        with:
          repository: infralight/helm-values
          path: tmp/helm-values
          ref: master
      - name: "UPDATE IMAGE TAG"
        if: ${{ env.NEW_APP_NAME }}
        run: |
          cd tmp/helm-values
          yq eval -i '.base.tag=${{ inputs.tagKey }}' tmp/helm-values/dev/${{ inputs.environment }}/${{ inputs.app-name }}.yaml
      - uses: EndBug/add-and-commit@v9
        if: ${{ env.NEW_APP_NAME }}
        with:
          cwd: 'tmp/helm-values/dev/${{ inputs.environment }}'
          message: ${{ env.NEW_APP_NAME }} image updated to ${{ inputs.tagKey }}'
      - name: "[ArgoCD]: modify application revision target to ${{inputs.branch}}"
        uses: clowdhaus/argo-cd-action/@v2.0.0
        if: ${{ !inputs.skipRevision && !env.NEW_APP_NAME }}
        with:
          command: app set "${{ env.APP_NAME }}"
          options: --revision ${{ inputs.branch }}
      - name: "[ArgoCD]: update docker image in ArgoCD Application ${{ env.APP_NAME }} tag to ${{ env.TAG }}"
        if: ${{ !env.NEW_APP_NAME }}
        uses: clowdhaus/argo-cd-action/@v2.0.0
        with:
          command: app set "${{ env.APP_NAME }}"
          options: --helm-set "${{ inputs.tagKey }}=${{ env.TAG }}"
      - name: "[ArgoCD]: trigger refresh"
        if: ${{ !env.NEW_APP_NAME }}
        uses: clowdhaus/argo-cd-action/@v2.0.0
        with:
          command: app get "${{ env.APP_NAME }}"
          options: --hard-refresh
      - name: "[ArgoCD]: trigger sync"
        if: ${{ !env.NEW_APP_NAME }}
        uses: clowdhaus/argo-cd-action/@v2.0.0
        with:
          command: app sync "${{ env.APP_NAME }}"
      - name: "[ArgoCD]: wait for deploy to complete"
        if: ${{ !env.NEW_APP_NAME }}
        uses: clowdhaus/argo-cd-action/@v2.0.0
        with:
          command: app wait ${{ env.APP_NAME }} --timeout ${{ inputs.timeout }}
      - name: "[ArgoCD]: trigger refresh"
        if: ${{ env.NEW_APP_NAME }}
        uses: clowdhaus/argo-cd-action/@v2.0.0
        with:
          command: app get "${{ env.NEW_APP_NAME }}"
          options: --hard-refresh
      - name: "[ArgoCD]: trigger sync"
        if: ${{ env.NEW_APP_NAME }}
        uses: clowdhaus/argo-cd-action/@v2.0.0
        with:
          command: app sync "${{ env.NEW_APP_NAME }}"
      - name: "[ArgoCD]: wait for deploy to complete"
        if: ${{ env.NEW_APP_NAME }}
        uses: clowdhaus/argo-cd-action/@v2.0.0
        with:
          command: app wait ${{ env.NEW_APP_NAME }} --timeout ${{ inputs.timeout }}
      - name: "Notify Slack of deployment status"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: https://firefly-app-assets.s3.us-east-1.amazonaws.com/logo/serenity.png
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "${{ env.APP_NAME }} ArgoCD successfully deployed from ${{ inputs.branch }} to ${{ inputs.environment }}, status: ${{ job.status }}"
          SLACK_TITLE: "**${{ inputs.environment }}**: ${{ env.APP_NAME }} ArgoCD deployment notification, status: ${{ job.status }}"
          SLACK_USERNAME: cicdBot
          SLACK_WEBHOOK: ${{ secrets.CI_SLACK_WEBHOOK }}
