name: Reusable Tag and Release

on:
  workflow_call:

jobs:
  tests:
    name: Build and Release Tag
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          RELEASE_BRANCHES: master
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          INITIAL_VERSION: 1.0.0
          PRERELEASE_SUFFIX: beta
          VERBOSE: true

