name: Reusable Release Tag

on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: master
        required: true

jobs:
  tests:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/${{ inputs.branch }}' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          release_branches: ${{ inputs.branch }}
          github_token: ${{ github.token }}
          tag_prefix: pkg/v
      - name: Bump beta version and push tag
        if: github.event_name == 'workflow_dispatch'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          pre_release_branches: .*
          github_token: ${{ github.token }}
          tag_prefix: pkg/v
