name: Reusable Golang Tests

on:
  workflow_call:
    inputs:
      go-version:
        default: '1.18.2'
        required: false
        type: string
      custom:
        type: boolean
        required: false
        default: false
      run:
        default: 'go test -v ./...'
        required: false
        type: string
    secrets:
      GLOBAL_PAT:
        required: false

permissions:
  contents: read

jobs:
  basic-tests:
    if: inputs.custom == false
    name: Run Basic Tests
    env:
      HAVE_GLOBAL_PAT: ${{ secrets.GLOBAL_PAT != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Configure git for private modules
        if: ${{ env.HAVE_GLOBAL_PAT == 'true' }}
        run: git config --global url."https://${{ secrets.GLOBAL_PAT }}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          cache: false
          go-version: ${{ inputs.go-version }}
      - name: Test
        run: |
          go version
          go vet ./...
          go test -v ./...
  custom-tests:
    if: inputs.custom == true
    name: Run Custom Tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Configure git for private modules
        if: ${{ env.HAVE_GLOBAL_PAT == 'true' }}
        run: git config --global url."https://${{ secrets.GLOBAL_PAT }}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          cache: false
          go-version: ${{ inputs.go-version }}
      - run: ${{ inputs.run }}
