name: Reusable Golang Build ECR Image

on:
  workflow_call:
    inputs:
      go-version:
        default: '1.18.2'
        required: false
        type: string
      custom:
        type: boolean
        required: false
        default: false
      run-tests:
        type: boolean
        required: false
        default: false
      trivy-scan:
        type: boolean
        required: false
        default: false
      custom-tests:
        type: boolean
        required: false
        default: false
      cmd-tests:
        type: string
        required: false
        default: "go test ./..."
      app-name:
        type: string
        required: true
      image-name:
        type: string
        required: true
      branch:
        type: string
        required: true
      event_name:
        type: string
        required: true
      image-tag:
        type: string
        required: false
      env:
        type: string
        default: 'dev'
        required: false
      dockerfile:
        type: string
        required: false
        default: 'Dockerfile'
      latest:
        type: boolean
        required: false
        default: false
      run:
        required: false
        type: string
    secrets:
      GLOBAL_PAT_USER:
        required: true
      GLOBAL_PAT:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      ACCOUNT_ID:
        required: true

jobs:
  tests:
    name: "Run Golang Tests"
    if: inputs.run-tests == true
    uses: ./.github/workflows/golang-tests.yaml
    with:
      go-version: ${{ inputs.go-version }}
      custom: ${{ inputs.custom-tests }}
      run: ${{ inputs.cmd-tests }}
    secrets:
      GLOBAL_PAT: ${{ secrets.GLOBAL_PAT }}
  build-push-ecr:
    name: "Build & Push ECR Docker Image "
    runs-on: 'ubuntu-latest'
    env:
      HAVE_GLOBAL_PAT: ${{ secrets.GLOBAL_PAT != '' }}
      HAVE_RUN_CMD: ${{ inputs.run != '' }}
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: "[Build] configure git for private modules"
        if: ${{ env.HAVE_GLOBAL_PAT == 'true' }}
        run: git config --global url."https://${{ secrets.GLOBAL_PAT }}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: "Build"
        if: ${{ env.HAVE_RUN_CMD == 'false' }}
        run: |
          make docker-build-${{ inputs.app-name }} ACCESS_TOKEN_USR=${{ secrets.GLOBAL_PAT_USER }} ACCESS_TOKEN_PWD=${{ secrets.GLOBAL_PAT }}
          docker tag docker.io/library/tempimage ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:latest
          docker tag docker.io/library/tempimage ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${GITHUB_SHA::6}
      - name: "Run Trivy vulnerability scanner"
        if: ${{ inputs.trivy-scan == 'true' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/library/tempimage
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: "configure aws credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: "login ecr"
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - name: "upload image"
        if: (env.HAVE_RUN_CMD == 'false')
        run: |
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${GITHUB_SHA::6}
          if ${{inputs.latest}}; then docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:latest; fi
      - name: "[Build]: build image & upload to ECR - CUSTOM"
        if: ${{ env.HAVE_RUN_CMD == 'true' }}
        run: ${{ inputs.run }}
