name: Reusable Golang Build ECR Image

on:
  workflow_call:
    inputs:
      go-version:
        default: '1.18.2'
        required: false
        type: string
      custom:
        type: boolean
        required: false
        default: false
      run-tests:
        type: boolean
        required: false
        default: false
      trivy-scan:
        type: boolean
        required: false
        default: false
      custom-tests:
        type: boolean
        required: false
        default: false
      cmd-tests:
        type: string
        required: false
        default: "go test ./..."
      app-name:
        type: string
        required: true
      image-name:
        type: string
        required: true
      branch:
        type: string
        required: true
      event_name:
        type: string
        required: true
      image-tag:
        type: string
        required: false
      prod:
        type: boolean
        default: false
        required: false
      dockerfile-path:
        type: string
        required: false
        default: '/'
      latest:
        type: boolean
        required: false
        default: false
      run:
        required: false
        type: string
    secrets:
      GLOBAL_PAT_USER:
        required: true
      GLOBAL_PAT:
        required: true
      STAG_AWS_ACCESS_KEY_ID:
        required: true
      PROD_AWS_ACCESS_KEY_ID:
        required: true
      STAG_AWS_SECRET_ACCESS_KEY:
        required: true
      PROD_AWS_SECRET_ACCESS_KEY:
        required: true
      STAG_ARGOCD_TOKEN:
        required: true
      PROD_ARGOCD_TOKEN:
        required: true
      STAG_AWS_REGION:
        required: true
      PROD_AWS_REGION:
        required: true
      STAG_ACCOUNT_ID:
        required: true
      PROD_ACCOUNT_ID:
        required: true

jobs:
  tests:
    name: "Run Golang Tests"
    if: inputs.run-tests == true
    uses: ./.github/workflows/golang-tests.yaml
    with:
      go-version: ${{ inputs.go-version }}
      custom: ${{ inputs.custom-tests }}
      run: ${{ inputs.cmd-tests }}
    secrets:
      GLOBAL_PAT: ${{ secrets.GLOBAL_PAT }}
  build-push-ecr:
    name: "Build & Push ECR Docker Image "
    runs-on: 'ubuntu-latest'
    env:
      HAVE_GLOBAL_PAT: ${{ secrets.GLOBAL_PAT != '' }}
      HAVE_RUN_CMD: ${{ inputs.run != '' }}
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: "[Build] configure git for private modules"
        if: ${{ env.HAVE_GLOBAL_PAT == 'true' }}
        run: git config --global url."https://${{ secrets.GLOBAL_PAT }}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: "Build"
        if: ${{ env.HAVE_RUN_CMD == 'false' }}
        run: |
          ls
          cd ${{ inputs.dockerfile-path }}
          docker buildx build . --file ${{ inputs.dockerfile-path }}/Dockerfile --build-arg ACCESS_TOKEN_USR=${{ secrets.GLOBAL_PAT_USER }} --build-arg ACCESS_TOKEN_PWD=${{ secrets.GLOBAL_PAT }} --tag docker.io/library/tempimage
          docker tag docker.io/library/tempimage ${{ secrets.STAG_ACCOUNT_ID }}.dkr.ecr.${{ secrets.STAG_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:latest
          docker tag docker.io/library/tempimage ${{ secrets.PROD_ACCOUNT_ID }}.dkr.ecr.${{ secrets.PROD_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:latest
          docker tag docker.io/library/tempimage ${{ secrets.STAG_ACCOUNT_ID }}.dkr.ecr.${{ secrets.STAG_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${GITHUB_SHA::6}
          docker tag docker.io/library/tempimage ${{ secrets.PROD_ACCOUNT_ID }}.dkr.ecr.${{ secrets.PROD_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${GITHUB_SHA::6}
      - name: "Run Trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/library/tempimage
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: "[stag] configure aws credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAG_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.STAG_AWS_REGION }}
      - name: "[stag] login ecr"
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr-stag
      - name: "[stag] upload image"
        if: (env.HAVE_RUN_CMD == 'false')
        run: |
          docker push ${{ secrets.STAG_ACCOUNT_ID }}.dkr.ecr.${{ secrets.STAG_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${GITHUB_SHA::6}
          if ${{inputs.latest}}; then docker push ${{ secrets.STAG_ACCOUNT_ID }}.dkr.ecr.${{ secrets.STAG_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:latest; fi
      - name: "[prod] configure aws credentials"
        if: (inputs.prod)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}
      - name: "[prod] login ecr"
        if: (inputs.prod)
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr-prod
      - name: "[prod] upload image"
        if: (env.HAVE_RUN_CMD == 'false' && inputs.prod)
        run: |
          docker push ${{ secrets.PROD_ACCOUNT_ID }}.dkr.ecr.${{ secrets.PROD_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${GITHUB_SHA::6}
          if ${{inputs.latest}}; then docker push ${{ secrets.PROD_ACCOUNT_ID }}.dkr.ecr.${{ secrets.PROD_AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:latest; fi
      - name: "[Build]: build image & upload to ECR stage - CUSTOM"
        if: ${{ env.HAVE_RUN_CMD == 'true' }}
        run: ${{ inputs.run }}
