name: Reusable Lambda Upload Sync

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: true
      lambda-name:
        type: string
        required: false
        default: ''
        description: Overrides app-name when setting lambda name
      branch:
        type: string
        required: true
      ecr-prefix:
        type: string
        required: false
        default: ''
      environment:
        type: string
        default: 'dev'
        required: false
    secrets:
      CI_SLACK_WEBHOOK:
        required: true
      CI_AWS_CRED_KEY:
        required: true
      CI_AWS_CRED_SECRET:
        required: true
      CI_REGION:
        required: true
      CI_ACCOUNT_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  lambda:
    environment: ${{ inputs.environment }}
    name: "[Lambda]"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v4
        env:
          environment: ${{ startsWith(inputs.environment, 'env') && 'dev' || inputs.environment }}
        with:
          role-to-assume: arn:aws:iam::${{ secrets.CI_ACCOUNT_ID }}:role/${{ env.environment }}-github-actions-oidc
          role-session-name: runner
          aws-region: ${{ secrets.CI_REGION }}

      - name: "[Lambda] Deploy"
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_region: ${{ secrets.CI_REGION }}
          function_name: ${{ inputs.lambda-name == '' && format('{0}-{1}', inputs.environment, inputs.app-name) || format('{0}-{1}', inputs.environment, inputs.lambda-name) }}
          image_uri: ${{ secrets.CI_ACCOUNT_ID }}.dkr.ecr.${{ secrets.CI_REGION }}.amazonaws.com/${{ inputs.ecr-prefix }}${{ inputs.app-name }}:latest

      - name: "Notify Slack of deployment status"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: https://firefly-app-assets.s3.us-east-1.amazonaws.com/logo/serenity.png
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "${{ inputs.app-name }} Lambda successfully deployed from ${{ inputs.branch }} to ${{ inputs.environment }}, status: ${{ job.status }}"
          SLACK_TITLE: "**${{ inputs.environment }}**: ${{ inputs.app-name }} Lambda deployment notification, status: ${{ job.status }}"
          SLACK_USERNAME: cicdBot
          SLACK_WEBHOOK: ${{ secrets.CI_SLACK_WEBHOOK }}
